# Generated by Django 6.0.1 on 2026-03-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['student_class', 'user__username']},
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_color',
            field=models.CharField(choices=[('rose', 'Rose'), ('blue', 'Blue'), ('emerald', 'Emerald'), ('purple', 'Purple'), ('amber', 'Amber')], default='rose', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City/Location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_help',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Class/Year'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
