# Generated by Django 6.0.1 on 2026-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_avatar_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_color',
            field=models.CharField(default='rose', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_class',
            field=models.CharField(blank=True, help_text='e.g., Class A, Section B', max_length=100, null=True),
        ),
    ]
