# Generated by Django 6.0.1 on 2026-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_assessment_assessmentsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentsubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
